version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: process.env.DB_LISTEN_PORT
      DB_NAME: mydatabase
      DB_USER: postgres
      DB_PASSWORD: password
    ports:
      - '3000:3000'
    depends_on:
      - db

volumes:
  db-data:
